/* Bilingual copy for the invitation — default Russian, English toggle.
   window.INVITE_COPY[lang].<section>  */
window.INVITE_COPY = {
  ru: {
    nav: { rsvp: 'Ответить' },
    hero: {
      eyebrow: 'Приглашение · 45-летие',
      name: 'Ляна',
      surname: 'Хабибуллина',
      occasion: 'Юбилейный вечер · 45 лет',
      tagline: 'Вечер из тысячи и одной истории',
      date: '9 августа 2026',
      venue: 'Baya Harahora · Нальчик',
      rsvp: 'Подтвердить участие',
      countdownTo: 'До начала вечера',
    },
    countdown: { days: 'дней', hours: 'часов', minutes: 'минут', seconds: 'секунд', done: 'Сегодня тот самый вечер' },
    invitation: {
      eyebrow: 'Приглашение',
      title: 'Тысяча и одна ночь',
      body: 'Когда на Кавказ опускается тёплая ночь, двери дворца отворяются для самых дорогих гостей. Нас ждёт вечер восточного великолепия и деко-роскоши — мерцание золота, аромат специй и музыка, что льётся до рассвета. Приходите разделить одну из тысячи и одной истории — нашу.',
    },
    details: {
      eyebrow: 'Детали',
      title: 'Вечер',
      items: [
        { k: 'Дата', v: '9 августа 2026, суббота' },
        { k: 'Прибытие', v: 'Золотой час · 18:00' },
        { k: 'Место', v: 'Baya Harahora' },
        { k: 'Адрес', v: 'Нальчик, Кабардино-Балкария' },
      ],
      parkingLabel: 'Парковка',
      parking: 'Бесплатная парковка для гостей у входа в ресторан.',
      maps: 'Открыть в картах',
      mapsHref: 'https://maps.google.com/?q=Baya+Harahora+Нальчик',
    },
    dress: {
      eyebrow: 'Дресс-код',
      title: 'Восточный блеск и деко-золото',
      subtitle: 'Самоцветные тона и золото',
      palette: [
        { c: '#16265C', n: 'Сапфир' },
        { c: '#1A9A72', n: 'Изумруд' },
        { c: '#9A2233', n: 'Рубин' },
        { c: '#6E4A9E', n: 'Аметист' },
        { c: 'var(--grad-gold)', n: 'Золото' },
      ],
      women: { h: 'Дамам', t: 'Длинные платья глубоких самоцветных тонов, шёлк и бархат, золотые украшения, изящная вышивка. Приветствуются восточные мотивы.' },
      men: { h: 'Господам', t: 'Тёмный костюм — сапфир, изумруд или чёрный, — золотые или бордовые акценты: галстук, платок, запонки.' },
    },
    night: {
      eyebrow: 'Что вас ждёт',
      title: 'Вечер впереди',
      teasers: [
        { h: 'Золотой час', t: 'Встреча на террасе с видом на горы, бокал игристого и тёплый кавказский закат.' },
        { h: 'Пир', t: 'Столы, что ломятся от восточных яств, специй и сладостей до глубокой ночи.' },
        { h: 'Музыка и танцы', t: 'Живая музыка, лезгинка и восточный танец — и танцпол, что не остынет до рассвета.' },
        { h: 'Интрига', t: 'Немного тайны, страсти и историй, которые рождаются лишь в такие ночи.' },
      ],
    },
    rsvp: {
      eyebrow: 'RSVP',
      title: 'Ваш ответ',
      subtitle: 'Пожалуйста, ответьте до 1 августа',
      name: 'Имя и фамилия',
      attending: 'Придёте?',
      yes: 'Да, буду',
      no: 'К сожалению, нет',
      guest: 'Имя сопровождающего (+1)',
      guestHint: 'Если придёте вдвоём',
      diet: 'Аллергии и предпочтения в еде',
      dietHint: 'Например: вегетарианское меню, без орехов',
      contact: 'Телефон или e-mail',
      contactHint: 'Чтобы мы могли с вами связаться',
      submit: 'Отправить ответ',
      required: 'Пожалуйста, заполните обязательные поля',
      successTitle: 'Ваше место за пиром забронировано',
      successBody: 'Благодарим за ответ. Мы бережно сохраним для вас место под золотыми сводами. До встречи на вечере из тысячи и одной истории.',
      successDecline: 'Спасибо, что дали знать. Нам будет вас не хватать — но мы поднимем бокал за вас.',
      again: 'Изменить ответ',
    },
    faq: {
      eyebrow: 'Вопросы',
      title: 'Часто спрашивают',
      items: [
        { q: 'Можно ли прийти с детьми?', a: 'Это вечер для взрослых — мы будем праздновать до глубокой ночи. Пожалуйста, оставьте малышей дома и отдохните вместе с нами.' },
        { q: 'Когда состоится вечер?', a: '9 августа 2026 года, суббота. Сбор гостей в золотой час, к 18:00.' },
        { q: 'Что подарить?', a: 'Ваше присутствие — лучший подарок. Если захотите большего, тёплое слово или цветы будут приняты с радостью.' },
        { q: 'К кому обратиться с вопросами?', a: 'Звоните или пишите хозяйке вечера: +7 916 827 35 59.' },
      ],
    },
    footer: {
      host: 'Ляна Хабибуллина',
      phone: '+7 916 827 35 59',
      phoneHref: 'tel:+79168273559',
      hashtagLabel: 'Делитесь снимками вечера',
      hashtag: '#1001НочьЛяны',
      closing: 'С любовью ждём вас',
    },
    admin: {
      title: 'Ответы гостей',
      empty: 'Пока нет ответов на этом устройстве.',
      export: 'Скачать CSV',
      clear: 'Очистить',
      close: 'Закрыть',
      count: 'ответов',
      coming: 'придут',
    },
  },

  en: {
    nav: { rsvp: 'RSVP' },
    hero: {
      eyebrow: 'Invitation · 45th Birthday',
      name: 'Lyana',
      surname: 'Khabibullina',
      occasion: 'A Milestone Evening · Turning 45',
      tagline: 'A night of a thousand and one tales',
      date: '9 August 2026',
      venue: 'Baya Harahora · Nalchik',
      rsvp: 'Reserve your place',
      countdownTo: 'Until the evening begins',
    },
    countdown: { days: 'days', hours: 'hours', minutes: 'minutes', seconds: 'seconds', done: 'Tonight is the night' },
    invitation: {
      eyebrow: 'The Invitation',
      title: 'A Thousand & One Nights',
      body: 'When a warm night settles over the Caucasus, the palace doors open for the dearest of guests. An evening of Eastern splendour and Deco glamour awaits — shimmering gold, the scent of spice, and music that pours on until dawn. Come share one of a thousand and one tales — ours.',
    },
    details: {
      eyebrow: 'Details',
      title: 'The Evening',
      items: [
        { k: 'Date', v: 'Saturday, 9 August 2026' },
        { k: 'Arrival', v: 'Golden hour · 6:00 pm' },
        { k: 'Venue', v: 'Baya Harahora' },
        { k: 'Address', v: 'Nalchik, Kabardino-Balkaria' },
      ],
      parkingLabel: 'Parking',
      parking: 'Complimentary guest parking at the restaurant entrance.',
      maps: 'Open in Maps',
      mapsHref: 'https://maps.google.com/?q=Baya+Harahora+Nalchik',
    },
    dress: {
      eyebrow: 'Dress Code',
      title: 'Eastern Glamour meets Deco Gold',
      subtitle: 'Jewel tones & gold',
      palette: [
        { c: '#16265C', n: 'Sapphire' },
        { c: '#1A9A72', n: 'Emerald' },
        { c: '#9A2233', n: 'Ruby' },
        { c: '#6E4A9E', n: 'Amethyst' },
        { c: 'var(--grad-gold)', n: 'Gold' },
      ],
      women: { h: 'For Her', t: 'Floor-length gowns in deep jewel tones, silk and velvet, gold jewellery and fine embroidery. Eastern motifs are warmly welcome.' },
      men: { h: 'For Him', t: 'A dark suit — sapphire, emerald or black — with gold or burgundy accents: a tie, a pocket square, cufflinks.' },
    },
    night: {
      eyebrow: 'What awaits',
      title: 'The Night Ahead',
      teasers: [
        { h: 'Golden Hour', t: 'A welcome on the terrace beneath the mountains, sparkling in hand and a warm Caucasus sunset.' },
        { h: 'The Feast', t: 'Tables laden with Eastern delicacies, spice and sweetness, late into the night.' },
        { h: 'Music & Dance', t: 'Live music, lezginka and belly dance — and a dance floor that won’t cool until dawn.' },
        { h: 'Intrigue', t: 'A little mystery, a little passion, and the kind of stories born only on nights like this.' },
      ],
    },
    rsvp: {
      eyebrow: 'RSVP',
      title: 'Your Reply',
      subtitle: 'Kindly respond by 1 August',
      name: 'Full name',
      attending: 'Will you attend?',
      yes: 'Yes, I’ll be there',
      no: 'Sadly, I can’t',
      guest: 'Name of your guest (+1)',
      guestHint: 'If you’re bringing someone',
      diet: 'Allergies & dietary needs',
      dietHint: 'e.g. vegetarian, no nuts',
      contact: 'Phone or e-mail',
      contactHint: 'So we can reach you',
      submit: 'Send reply',
      required: 'Please fill in the required fields',
      successTitle: 'Your seat at the feast is reserved',
      successBody: 'Thank you for your reply. We’ll keep a place for you beneath the golden arches. Until the night of a thousand and one tales.',
      successDecline: 'Thank you for letting us know. You’ll be missed — we’ll raise a glass to you.',
      again: 'Edit my reply',
    },
    faq: {
      eyebrow: 'Questions',
      title: 'Frequently Asked',
      items: [
        { q: 'Can I bring children?', a: 'This is a grown-ups’ evening — we’ll celebrate late into the night. Please leave the little ones at home and enjoy a night off with us.' },
        { q: 'When does it take place?', a: 'Saturday, 9 August 2026. Guests gather at golden hour, around 6:00 pm.' },
        { q: 'What about gifts?', a: 'Your presence is the finest gift. Should you wish for more, a warm word or flowers will be received with joy.' },
        { q: 'Who do I contact with questions?', a: 'Call or message the host: +7 916 827 35 59.' },
      ],
    },
    footer: {
      host: 'Lyana Khabibullina',
      phone: '+7 916 827 35 59',
      phoneHref: 'tel:+79168273559',
      hashtagLabel: 'Share your photos of the night',
      hashtag: '#1001NightsOfLyana',
      closing: 'With love, we await you',
    },
    admin: {
      title: 'Guest replies',
      empty: 'No replies on this device yet.',
      export: 'Download CSV',
      clear: 'Clear',
      close: 'Close',
      count: 'replies',
      coming: 'attending',
    },
  },
};
